# Generated by Django 3.1.5 on 2021-01-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('STYLE', 'style'), ('POLITICS', 'politics'), ('DESIGN', 'design'), ('SCIENCE', 'science'), ('HEALTH', 'health'), ('OPINION', 'opinion'), ('TRAVEL', 'travel'), ('WORLD', 'world'), ('CULTURE', 'culture'), ('BUSINESS', 'business'), ('ENVIRONMENT', 'environment')], default='world', max_length=50),
        ),
    ]
