# Generated by Django 3.1.5 on 2021-01-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210119_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('WORLD', 'world'), ('SCIENCE', 'science'), ('TRAVEL', 'travel'), ('OPINION', 'opinion'), ('BUSINESS', 'business'), ('CULTURE', 'culture'), ('ENVIRONMENT', 'environment'), ('STYLE', 'style'), ('POLITICS', 'politics'), ('HEALTH', 'health'), ('DESIGN', 'design')], default='WORLD', max_length=50),
        ),
    ]
